module(load="imudp")
input(type="imudp" port="514")

template(
    name="RemoteLogs"
    type="string"
    string="/var/log/remote/%HOSTNAME%/%PROGRAMNAME%.log"
)

if $fromhost-ip != '127.0.0.1' then {
    action(
        type="omfile"
        dynaFile="RemoteLogs"
        createDirs="on"
    )
    stop
}